package com.alx4j.jab4j.reader.capture.media.sample;

/**
 * Concrete module sampling geometry generated by the phase search.
 *
 * @param centerXPx horizontal module center in normalized pixels
 * @param centerYPx vertical module center in normalized pixels
 * @param moduleSizePx module size in normalized pixels
 * @param centerOffsetXPx horizontal offset from the nominal module center
 * @param centerOffsetYPx vertical offset from the nominal module center
 * @param moduleSizeScale scale applied to the nominal module size
 */
public record CaptureMediaModulePhaseGeometry(
        double centerXPx,
        double centerYPx,
        double moduleSizePx,
        double centerOffsetXPx,
        double centerOffsetYPx,
        double moduleSizeScale
) {

    private static final double EPSILON = 0.000_001d;

    /**
     * Creates validated module sampling geometry.
     *
     * @param centerXPx horizontal module center
     * @param centerYPx vertical module center
     * @param moduleSizePx module size
     * @param centerOffsetXPx horizontal offset from nominal
     * @param centerOffsetYPx vertical offset from nominal
     * @param moduleSizeScale module-size scale
     */
    public CaptureMediaModulePhaseGeometry {
        requireFinite(centerXPx, "centerXPx");
        requireFinite(centerYPx, "centerYPx");
        if (!Double.isFinite(moduleSizePx) || moduleSizePx <= 0.0d) {
            throw new IllegalArgumentException("moduleSizePx must be finite and positive");
        }
        requireFinite(centerOffsetXPx, "centerOffsetXPx");
        requireFinite(centerOffsetYPx, "centerOffsetYPx");
        if (!Double.isFinite(moduleSizeScale) || moduleSizeScale <= 0.0d) {
            throw new IllegalArgumentException("moduleSizeScale must be finite and positive");
        }
    }

    /**
     * Returns true when the center differs from the nominal module center.
     *
     * @return whether a bounded center shift is active
     */
    public boolean centerShifted() {
        return Math.abs(centerOffsetXPx) > EPSILON || Math.abs(centerOffsetYPx) > EPSILON;
    }

    /**
     * Returns true when the module size differs from the nominal module size.
     *
     * @return whether a bounded module-size scale variant is active
     */
    public boolean scaleShifted() {
        return Math.abs(moduleSizeScale - 1.0d) > EPSILON;
    }

    private static void requireFinite(double value, String fieldName) {
        if (!Double.isFinite(value)) {
            throw new IllegalArgumentException(fieldName + " must be finite");
        }
    }
}
